version: "3"

services:
    node:
        container_name: reward_coordinator
        build: ./reward_coordinator
        ports:
            - "9000:9000"
        stdin_open: true
        tty: true

    python:
        container_name: reward_calculator
        build: ./reward_calculator
        ports:
            - "9001:9001"
        stdin_open: true
        tty: true

    ethereum:
        image: ethereum/client-go
        ports:
            - "8545:8545"
            - "30303:30303"

