version: "3"
# see https://docs.docker.com/cloud/ecs-compose-examples/ for help

services:
    node:
        container_name: reward_coordinator
        image: 376538560806.dkr.ecr.us-west-2.amazonaws.com/reward_coordinator
        ports:
            - "9000:9000"
        stdin_open: true
        tty: true
        x-aws-logs_retention: 10

    python:
        container_name: reward_calculator
        image: 376538560806.dkr.ecr.us-west-2.amazonaws.com/reward_calculator
        ports:
            - "9001:9001"
        stdin_open: true
        tty: true
        x-aws-logs_retention: 10

