version: "3"

services:
    node:
        container_name: reward_coordinator
        build: ./reward_coordinator
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true

    python:
        container_name: reward_calculator
        build: ./reward_calculator
        ports:
            - "8001:8001"
        stdin_open: true
        tty: true
