version: "3"

services:
    node:
        container_name: reward_coordinator
        image: 376538560806.dkr.ecr.us-west-2.amazonaws.com/reward_coordinator
        ports:
            - "9000:9000"
        stdin_open: true
        tty: true
        env_file:
          - local.env

    python:
        container_name: reward_calculator
        image: 376538560806.dkr.ecr.us-west-2.amazonaws.com/reward_calculator
        ports:
            - "9001:9001"
        stdin_open: true
        tty: true

