version: "3.8"

services:
    node:
        container_name: reward_coordinator
        build: ./node
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true

    python:
        container_name: reward_calculator
        build: ./python
        ports:
            - "8001:8001"
        stdin_open: true
        tty: true
