version: "3"

services:
    node:
        container_name: reward_coordinator
        build: ./reward_coordinator
        ports:
            - "9000:9000"
        stdin_open: true
        tty: true
        environment:
          LITHIUM_SUBGRAPH_URI: 'http://docker-graph-node-1:8000/subgraphs/name/scaffold-eth/your-contract'
          REWARD_CALCULATOR_URI: 'http://reward_calculator:9001'
          COORDINATER_KEY: 'df57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e'
          FETCH_INTERVAL: 30000
          ETH_NODE: 'http://host.docker.internal:8545'

    python:
        container_name: reward_calculator
        build: ./reward_calculator
        ports:
            - "9001:9001"
        stdin_open: true
        tty: true

