version: "3"
# see https://docs.docker.com/cloud/ecs-compose-examples/ for help

services:
    node:
        container_name: reward_coordinator
        image: 376538560806.dkr.ecr.us-west-2.amazonaws.com/reward_coordinator
        ports:
            - "9000:9000"
        stdin_open: true
        tty: true
        environment:
            LITHIUM_SUBGRAPH_URI: ${LITHIUM_SUBGRAPH_URI}
            REWARD_CALCULATOR_URI: ${REWARD_CALCULATOR_URI}
            FETCH_INTERVAL: ${FETCH_INTERVAL}
            ETH_NODE: ${ETH_NODE}
            TARGET_CHAIN: ${TARGET_CHAIN}
            COORDINATOR_KEY: ${COORDINATOR_KEY}
        x-aws-logs_retention: 10

    python:
        container_name: reward_calculator
        image: 376538560806.dkr.ecr.us-west-2.amazonaws.com/reward_calculator
        ports:
            - "9001:9001"
        stdin_open: true
        tty: true
        environment:
            LITHIUM_SUBGRAPH_URI: ${LITHIUM_SUBGRAPH_URI}
            REWARD_CALCULATOR_URI: ${REWARD_CALCULATOR_URI}
            FETCH_INTERVAL: ${FETCH_INTERVAL}
            ETH_NODE: ${ETH_NODE}
            TARGET_CHAIN: ${TARGET_CHAIN}
            COORDINATOR_KEY: ${COORDINATOR_KEY}
        x-aws-logs_retention: 10

